// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=628bd1a34d4ac01b70e7dad1a2e3d9aec099663c$
//

#ifndef CEF_INCLUDE_CAPI_CEF_COMMAND_LINE_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_CEF_COMMAND_LINE_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_base_capi.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _cef_command_line_0_t {
  cef_base_ref_counted_t base;
  int (CEF_CALLBACK *is_valid)(struct _cef_command_line_0_t* self);
  int (CEF_CALLBACK *is_read_only)(struct _cef_command_line_0_t* self);
  struct _cef_command_line_0_t* (CEF_CALLBACK *copy)(struct _cef_command_line_0_t* self);
  void (CEF_CALLBACK *init_from_argv)(struct _cef_command_line_0_t* self, int argc, const char* const* argv);
  void (CEF_CALLBACK *init_from_string)(struct _cef_command_line_0_t* self, const cef_string_t* command_line);
  void (CEF_CALLBACK *reset)(struct _cef_command_line_0_t* self);
  void (CEF_CALLBACK *get_argv)(struct _cef_command_line_0_t* self, cef_string_list_t argv);
  cef_string_userfree_t (CEF_CALLBACK *get_command_line_string)(struct _cef_command_line_0_t* self);
  cef_string_userfree_t (CEF_CALLBACK *get_program)(struct _cef_command_line_0_t* self);
  void (CEF_CALLBACK *set_program)(struct _cef_command_line_0_t* self, const cef_string_t* program);
  int (CEF_CALLBACK *has_switches)(struct _cef_command_line_0_t* self);
  int (CEF_CALLBACK *has_switch)(struct _cef_command_line_0_t* self, const cef_string_t* name);
  cef_string_userfree_t (CEF_CALLBACK *get_switch_value)(struct _cef_command_line_0_t* self, const cef_string_t* name);
  void (CEF_CALLBACK *get_switches)(struct _cef_command_line_0_t* self, cef_string_map_t switches);
  void (CEF_CALLBACK *append_switch)(struct _cef_command_line_0_t* self, const cef_string_t* name);
  void (CEF_CALLBACK *append_switch_with_value)(struct _cef_command_line_0_t* self, const cef_string_t* name, const cef_string_t* value);
  int (CEF_CALLBACK *has_arguments)(struct _cef_command_line_0_t* self);
  void (CEF_CALLBACK *get_arguments)(struct _cef_command_line_0_t* self, cef_string_list_t arguments);
  void (CEF_CALLBACK *append_argument)(struct _cef_command_line_0_t* self, const cef_string_t* argument);
  void (CEF_CALLBACK *prepend_wrapper)(struct _cef_command_line_0_t* self, const cef_string_t* wrapper);
} cef_command_line_0_t;

typedef struct _cef_command_line_14100_t {
  cef_base_ref_counted_t base;
  int (CEF_CALLBACK *is_valid)(struct _cef_command_line_14100_t* self);
  int (CEF_CALLBACK *is_read_only)(struct _cef_command_line_14100_t* self);
  struct _cef_command_line_0_t* (CEF_CALLBACK *copy)(struct _cef_command_line_14100_t* self);
  void (CEF_CALLBACK *init_from_argv)(struct _cef_command_line_14100_t* self, int argc, const char* const* argv);
  void (CEF_CALLBACK *init_from_string)(struct _cef_command_line_14100_t* self, const cef_string_t* command_line);
  void (CEF_CALLBACK *reset)(struct _cef_command_line_14100_t* self);
  void (CEF_CALLBACK *get_argv)(struct _cef_command_line_14100_t* self, cef_string_list_t argv);
  cef_string_userfree_t (CEF_CALLBACK *get_command_line_string)(struct _cef_command_line_14100_t* self);
  cef_string_userfree_t (CEF_CALLBACK *get_program)(struct _cef_command_line_14100_t* self);
  void (CEF_CALLBACK *set_program)(struct _cef_command_line_14100_t* self, const cef_string_t* program);
  int (CEF_CALLBACK *has_switches)(struct _cef_command_line_14100_t* self);
  int (CEF_CALLBACK *has_switch)(struct _cef_command_line_14100_t* self, const cef_string_t* name);
  cef_string_userfree_t (CEF_CALLBACK *get_switch_value)(struct _cef_command_line_14100_t* self, const cef_string_t* name);
  void (CEF_CALLBACK *get_switches)(struct _cef_command_line_14100_t* self, cef_string_map_t switches);
  void (CEF_CALLBACK *append_switch)(struct _cef_command_line_14100_t* self, const cef_string_t* name);
  void (CEF_CALLBACK *append_switch_with_value)(struct _cef_command_line_14100_t* self, const cef_string_t* name, const cef_string_t* value);
  int (CEF_CALLBACK *has_arguments)(struct _cef_command_line_14100_t* self);
  void (CEF_CALLBACK *get_arguments)(struct _cef_command_line_14100_t* self, cef_string_list_t arguments);
  void (CEF_CALLBACK *append_argument)(struct _cef_command_line_14100_t* self, const cef_string_t* argument);
  void (CEF_CALLBACK *prepend_wrapper)(struct _cef_command_line_14100_t* self, const cef_string_t* wrapper);
  void (CEF_CALLBACK *remove_switch)(struct _cef_command_line_14100_t* self, const cef_string_t* name);
} cef_command_line_14100_t;

CEF_EXPORT cef_command_line_0_t* cef_command_line_create(void);
CEF_EXPORT cef_command_line_0_t* cef_command_line_get_global(void);

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_COMMAND_LINE_CAPI_VERSIONS_H_
