// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=76ed12c4baf44a225505cac646b3683ba32987f9$
//

#ifndef CEF_INCLUDE_CAPI_CEF_PARSER_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_CEF_PARSER_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_base_capi.h"

#ifdef __cplusplus
extern "C" {
#endif

CEF_EXPORT int cef_resolve_url(const cef_string_t* base_url, const cef_string_t* relative_url, cef_string_t* resolved_url);
CEF_EXPORT int cef_parse_url(const cef_string_t* url, struct _cef_urlparts_t* parts);
CEF_EXPORT int cef_create_url(const struct _cef_urlparts_t* parts, cef_string_t* url);
CEF_EXPORT cef_string_userfree_t cef_format_url_for_security_display(const cef_string_t* origin_url);
CEF_EXPORT cef_string_userfree_t cef_get_mime_type(const cef_string_t* extension);
CEF_EXPORT void cef_get_extensions_for_mime_type(const cef_string_t* mime_type, cef_string_list_t extensions);
CEF_EXPORT cef_string_userfree_t cef_base64_encode(const void* data, size_t data_size);
CEF_EXPORT struct _cef_binary_value_0_t* cef_base64_decode(const cef_string_t* data);
CEF_EXPORT cef_string_userfree_t cef_uriencode(const cef_string_t* text, int use_plus);
CEF_EXPORT cef_string_userfree_t cef_uridecode(const cef_string_t* text, int convert_to_utf8, cef_uri_unescape_rule_t unescape_rule);
CEF_EXPORT struct _cef_value_0_t* cef_parse_json(const cef_string_t* json_string, cef_json_parser_options_t options);
CEF_EXPORT struct _cef_value_0_t* cef_parse_json_buffer(const void* json, size_t json_size, cef_json_parser_options_t options);
CEF_EXPORT struct _cef_value_0_t* cef_parse_jsonand_return_error(const cef_string_t* json_string, cef_json_parser_options_t options, cef_string_t* error_msg_out);
CEF_EXPORT cef_string_userfree_t cef_write_json(struct _cef_value_0_t* node, cef_json_writer_options_t options);

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_PARSER_CAPI_VERSIONS_H_
