// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=fb681fe904dc1c8baf10ebf1c3b1794397e602ea$
//

#ifndef CEF_INCLUDE_CAPI_CEF_RESOURCE_HANDLER_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_CEF_RESOURCE_HANDLER_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_base_capi.h"
#include "include/capi/cef_browser_capi_versions.h"
#include "include/capi/cef_callback_capi_versions.h"
#include "include/capi/cef_cookie_capi_versions.h"
#include "include/capi/cef_request_capi_versions.h"
#include "include/capi/cef_response_capi_versions.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _cef_resource_skip_callback_0_t {
  cef_base_ref_counted_t base;
  void (CEF_CALLBACK *cont)(struct _cef_resource_skip_callback_0_t* self, int64_t bytes_skipped);
} cef_resource_skip_callback_0_t;

typedef struct _cef_resource_read_callback_0_t {
  cef_base_ref_counted_t base;
  void (CEF_CALLBACK *cont)(struct _cef_resource_read_callback_0_t* self, int bytes_read);
} cef_resource_read_callback_0_t;

typedef struct _cef_resource_handler_0_t {
  cef_base_ref_counted_t base;
  int (CEF_CALLBACK *open)(struct _cef_resource_handler_0_t* self, struct _cef_request_0_t* request, int* handle_request, struct _cef_callback_0_t* callback);
  int (CEF_CALLBACK *process_request)(struct _cef_resource_handler_0_t* self, struct _cef_request_0_t* request, struct _cef_callback_0_t* callback);
  void (CEF_CALLBACK *get_response_headers)(struct _cef_resource_handler_0_t* self, struct _cef_response_0_t* response, int64_t* response_length, cef_string_t* redirectUrl);
  int (CEF_CALLBACK *skip)(struct _cef_resource_handler_0_t* self, int64_t bytes_to_skip, int64_t* bytes_skipped, struct _cef_resource_skip_callback_0_t* callback);
  int (CEF_CALLBACK *read)(struct _cef_resource_handler_0_t* self, void* data_out, int bytes_to_read, int* bytes_read, struct _cef_resource_read_callback_0_t* callback);
  int (CEF_CALLBACK *read_response)(struct _cef_resource_handler_0_t* self, void* data_out, int bytes_to_read, int* bytes_read, struct _cef_callback_0_t* callback);
  void (CEF_CALLBACK *cancel)(struct _cef_resource_handler_0_t* self);
} cef_resource_handler_0_t;

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_RESOURCE_HANDLER_CAPI_VERSIONS_H_
