// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=5b3d4c3e25f4c10b71d6b62c12b30f057ea1004a$
//

#ifndef CEF_INCLUDE_CAPI_CEF_PERMISSION_HANDLER_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_CEF_PERMISSION_HANDLER_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_base_capi.h"
#include "include/capi/cef_browser_capi_versions.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _cef_media_access_callback_0_t {
  cef_base_ref_counted_t base;
  void (CEF_CALLBACK *cont)(struct _cef_media_access_callback_0_t* self, uint32_t allowed_permissions);
  void (CEF_CALLBACK *cancel)(struct _cef_media_access_callback_0_t* self);
} cef_media_access_callback_0_t;

typedef struct _cef_permission_prompt_callback_0_t {
  cef_base_ref_counted_t base;
  void (CEF_CALLBACK *cont)(struct _cef_permission_prompt_callback_0_t* self, cef_permission_request_result_t result);
} cef_permission_prompt_callback_0_t;

typedef struct _cef_permission_handler_0_t {
  cef_base_ref_counted_t base;
  int (CEF_CALLBACK *on_request_media_access_permission)(struct _cef_permission_handler_0_t* self, struct _cef_browser_0_t* browser, struct _cef_frame_0_t* frame, const cef_string_t* requesting_origin, uint32_t requested_permissions, struct _cef_media_access_callback_0_t* callback);
  int (CEF_CALLBACK *on_show_permission_prompt)(struct _cef_permission_handler_0_t* self, struct _cef_browser_0_t* browser, uint64_t prompt_id, const cef_string_t* requesting_origin, uint32_t requested_permissions, struct _cef_permission_prompt_callback_0_t* callback);
  void (CEF_CALLBACK *on_dismiss_permission_prompt)(struct _cef_permission_handler_0_t* self, struct _cef_browser_0_t* browser, uint64_t prompt_id, cef_permission_request_result_t result);
} cef_permission_handler_0_t;

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_PERMISSION_HANDLER_CAPI_VERSIONS_H_
