// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=c6d0789a4874970af93e34224f784e0e665fcff2$
//

#ifndef CEF_INCLUDE_CAPI_CEF_RESPONSE_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_CEF_RESPONSE_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_base_capi.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _cef_response_0_t {
  cef_base_ref_counted_t base;
  int (CEF_CALLBACK *is_read_only)(struct _cef_response_0_t* self);
  cef_errorcode_t (CEF_CALLBACK *get_error)(struct _cef_response_0_t* self);
  void (CEF_CALLBACK *set_error)(struct _cef_response_0_t* self, cef_errorcode_t error);
  int (CEF_CALLBACK *get_status)(struct _cef_response_0_t* self);
  void (CEF_CALLBACK *set_status)(struct _cef_response_0_t* self, int status);
  cef_string_userfree_t (CEF_CALLBACK *get_status_text)(struct _cef_response_0_t* self);
  void (CEF_CALLBACK *set_status_text)(struct _cef_response_0_t* self, const cef_string_t* statusText);
  cef_string_userfree_t (CEF_CALLBACK *get_mime_type)(struct _cef_response_0_t* self);
  void (CEF_CALLBACK *set_mime_type)(struct _cef_response_0_t* self, const cef_string_t* mimeType);
  cef_string_userfree_t (CEF_CALLBACK *get_charset)(struct _cef_response_0_t* self);
  void (CEF_CALLBACK *set_charset)(struct _cef_response_0_t* self, const cef_string_t* charset);
  cef_string_userfree_t (CEF_CALLBACK *get_header_by_name)(struct _cef_response_0_t* self, const cef_string_t* name);
  void (CEF_CALLBACK *set_header_by_name)(struct _cef_response_0_t* self, const cef_string_t* name, const cef_string_t* value, int overwrite);
  void (CEF_CALLBACK *get_header_map)(struct _cef_response_0_t* self, cef_string_multimap_t headerMap);
  void (CEF_CALLBACK *set_header_map)(struct _cef_response_0_t* self, cef_string_multimap_t headerMap);
  cef_string_userfree_t (CEF_CALLBACK *get_url)(struct _cef_response_0_t* self);
  void (CEF_CALLBACK *set_url)(struct _cef_response_0_t* self, const cef_string_t* url);
} cef_response_0_t;

CEF_EXPORT cef_response_0_t* cef_response_create(void);

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_RESPONSE_CAPI_VERSIONS_H_
