// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=52594ad25a4a3f6f86576be6cb7738b22ca5010a$
//

#ifndef CEF_INCLUDE_CAPI_VIEWS_CEF_MENU_BUTTON_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_VIEWS_CEF_MENU_BUTTON_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_menu_model_capi_versions.h"
#include "include/capi/views/cef_label_button_capi_versions.h"
#include "include/capi/views/cef_menu_button_delegate_capi_versions.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _cef_menu_button_0_t {
  cef_label_button_0_t base;
  void (CEF_CALLBACK *show_menu)(struct _cef_menu_button_0_t* self, struct _cef_menu_model_0_t* menu_model, const cef_point_t* screen_point, cef_menu_anchor_position_t anchor_position);
  void (CEF_CALLBACK *trigger_menu)(struct _cef_menu_button_0_t* self);
} cef_menu_button_0_t;

CEF_EXPORT cef_menu_button_0_t* cef_menu_button_create(struct _cef_menu_button_delegate_0_t* delegate, const cef_string_t* text);

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_VIEWS_CEF_MENU_BUTTON_CAPI_VERSIONS_H_
