// Copyright (c) 2026 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file is generated by the make_colorids_header.py tool.
//

#ifndef CEF_INCLUDE_CEF_COLOR_IDS_H_
#define CEF_INCLUDE_CEF_COLOR_IDS_H_
#pragma once

#include "include/base/cef_build.h"

// Undefine the macros that will be defined in this file.
// This avoids previous definition conflicts with Chromium.
#undef CHROME_COLOR_IDS
#undef COLOR_IDS
#undef COMPONENTS_COLOR_IDS

// ---------------------------------------------------------------------------
// From color_a.inc:

#define COLOR_IDS \
  CEF_ColorAlpha,
#define COMPONENTS_COLOR_IDS \
  CEF_ColorComponent,

// ---------------------------------------------------------------------------
// From color_b.inc:

#define COLOR_IDS \
  CEF_ColorBeta,
#if defined(OS_WIN)
#define CHROME_COLOR_IDS \
  CEF_ChromeColorsMarker,
#endif

#include "include/base/internal/cef_color_id_macros.inc"

#ifdef __cplusplus
extern "C" {
#endif

///
/// All input, intermediary, and output colors known to CEF/Chromium.
/// Clients can optionally extend this enum with additional values.
/// Clients define enum values from CEF_ChromeColorsEnd. Values named
/// beginning with "CEF_Color" represent the actual colors; the rest are
/// markers.
///
typedef enum {
  CEF_UiColorsStart = 0,

  COLOR_IDS

  CEF_UiColorsEnd,

  CEF_ComponentsColorsStart = CEF_UiColorsEnd,

  COMPONENTS_COLOR_IDS

  CEF_ComponentsColorsEnd,

  CEF_ChromeColorsStart = CEF_ComponentsColorsEnd,

  CHROME_COLOR_IDS

  // Clients must start custom color IDs from this value.
  CEF_ChromeColorsEnd,

  // Clients must not assign IDs larger than this value. This is used to
  // verify that color IDs and color set IDs are not interchanged.
  CEF_UiColorsLast = 0xffff
} cef_color_id_t;

#ifdef __cplusplus
}
#endif

// Note that this second include is not redundant. The second inclusion of the
// .inc file serves to undefine the macros the first inclusion defined.
#include "include/base/internal/cef_color_id_macros.inc"

// Undefine the macros that were defined in this file.
#undef CHROME_COLOR_IDS
#undef COLOR_IDS
#undef COMPONENTS_COLOR_IDS

#endif  // CEF_INCLUDE_CEF_COLOR_IDS_H_
