// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=25c9aeabb95023fc35a368a7a1b63fe7376f77c1$
//

#include "include/cef_api_hash.h"
#include "libcef_dll/cpptoc/request_cpptoc.h"
#include "libcef_dll/cpptoc/test/test_server_connection_cpptoc.h"
#include "libcef_dll/cpptoc/test/test_server_cpptoc.h"
#include "libcef_dll/ctocpp/test/test_server_handler_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"


// VIRTUAL METHODS FOR VERSION 0 - Body may be edited by hand.

NO_SANITIZE("cfi-icall") bool CefTestServerHandler_0_CToCpp::OnTestServerRequest(CefRefPtr<CefTestServer> server, CefRefPtr<CefRequest> request, CefRefPtr<CefTestServerConnection> connection) {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->on_test_server_request) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: server; type: refptr_diff
  DCHECK(server.get());
  if (!server.get()) {
    return false;
  }
  // Verify param: request; type: refptr_diff
  DCHECK(request.get());
  if (!request.get()) {
    return false;
  }
  // Verify param: connection; type: refptr_diff
  DCHECK(connection.get());
  if (!connection.get()) {
    return false;
  }

  // Execute
  int _retval = _struct->on_test_server_request(_struct,
      CefTestServerCppToC_Wrap(server),
      CefRequestCppToC_Wrap(request),
      CefTestServerConnectionCppToC_Wrap(connection));

  // Return type: bool
  return _retval?true:false;
}

// CONSTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefTestServerHandler_0_CToCpp::CefTestServerHandler_0_CToCpp() {
  const int version = cef_api_version();
  LOG_IF(FATAL, version < 0) << __func__ << " called with invalid version " << version;
}

// DESTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefTestServerHandler_0_CToCpp::~CefTestServerHandler_0_CToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template<> cef_test_server_handler_0_t* CefCToCppRefCounted<CefTestServerHandler_0_CToCpp, CefTestServerHandler, cef_test_server_handler_0_t>::UnwrapDerived(CefWrapperType type, CefTestServerHandler* c) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefWrapperType CefCToCppRefCounted<CefTestServerHandler_0_CToCpp, CefTestServerHandler, cef_test_server_handler_0_t>::kWrapperType = WT_TEST_SERVER_HANDLER;


