// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=6517234cdad5588fd2a8b1745931ef57c915e364$
//

#include "include/cef_api_hash.h"
#include "libcef_dll/cpptoc/views/box_layout_cpptoc.h"
#include "libcef_dll/cpptoc/views/fill_layout_cpptoc.h"
#include "libcef_dll/cpptoc/views/view_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS FOR VERSION 0 - Body may be edited by hand.

void CEF_CALLBACK box_layout_set_flex_for_view(struct _cef_box_layout_0_t* self, struct _cef_view_0_t* view, int flex) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: view; type: refptr_same
  DCHECK(view);
  if (!view) {
    return;
  }

  // Execute
  CefBoxLayout_0_CppToC::Get(self)->SetFlexForView(
      CefViewCppToC_Unwrap(view),
      flex);
}

void CEF_CALLBACK box_layout_clear_flex_for_view(struct _cef_box_layout_0_t* self, struct _cef_view_0_t* view) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: view; type: refptr_same
  DCHECK(view);
  if (!view) {
    return;
  }

  // Execute
  CefBoxLayout_0_CppToC::Get(self)->ClearFlexForView(
      CefViewCppToC_Unwrap(view));
}

cef_box_layout_0_t* CEF_CALLBACK box_layout_as_box_layout(struct _cef_layout_0_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return NULL;
  }

  // Execute
  CefRefPtr<CefBoxLayout> _retval = CefBoxLayout_0_CppToC::Get(reinterpret_cast<cef_box_layout_0_t*>(self))->AsBoxLayout();

  // Return type: refptr_same
  return CefBoxLayoutCppToC_Wrap(_retval);
}

struct _cef_fill_layout_0_t* CEF_CALLBACK box_layout_as_fill_layout(struct _cef_layout_0_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return NULL;
  }

  // Execute
  CefRefPtr<CefFillLayout> _retval = CefBoxLayout_0_CppToC::Get(reinterpret_cast<cef_box_layout_0_t*>(self))->AsFillLayout();

  // Return type: refptr_same
  return CefFillLayoutCppToC_Wrap(_retval);
}

int CEF_CALLBACK box_layout_is_valid(struct _cef_layout_0_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  bool _retval = CefBoxLayout_0_CppToC::Get(reinterpret_cast<cef_box_layout_0_t*>(self))->IsValid();

  // Return type: bool
  return _retval;
}

}  // namespace

// CONSTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefBoxLayout_0_CppToC::CefBoxLayout_0_CppToC() {
  const int version = cef_api_version();
  LOG_IF(FATAL, version < 0) << __func__ << " called with invalid version " << version;

  GetStruct()->set_flex_for_view = box_layout_set_flex_for_view;
  GetStruct()->clear_flex_for_view = box_layout_clear_flex_for_view;
  GetStruct()->base.as_box_layout = box_layout_as_box_layout;
  GetStruct()->base.as_fill_layout = box_layout_as_fill_layout;
  GetStruct()->base.is_valid = box_layout_is_valid;
}

// DESTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefBoxLayout_0_CppToC::~CefBoxLayout_0_CppToC() {
  shutdown_checker::AssertNotShutdown();
}

template<> CefRefPtr<CefBoxLayout> CefCppToCRefCounted<CefBoxLayout_0_CppToC, CefBoxLayout, cef_box_layout_0_t>::UnwrapDerived(CefWrapperType type, cef_box_layout_0_t* s) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefWrapperType CefCppToCRefCounted<CefBoxLayout_0_CppToC, CefBoxLayout, cef_box_layout_0_t>::kWrapperType = WT_BOX_LAYOUT;


