// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=ff344cfa76713510e255f50d3229574a46b90d91$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_VIEWS_DISPLAY_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_VIEWS_DISPLAY_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/views/cef_display.h"
#include "include/capi/views/cef_display_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefDisplay_0_CppToC
    : public CefCppToCRefCounted<CefDisplay_0_CppToC, CefDisplay, cef_display_0_t> {
 public:
  CefDisplay_0_CppToC();
  virtual ~CefDisplay_0_CppToC();
};

constexpr auto CefDisplayCppToC_Wrap = CefDisplay_0_CppToC::Wrap;
constexpr auto CefDisplayCppToC_Unwrap = CefDisplay_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_VIEWS_DISPLAY_CPPTOC_H_
