// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=81f83bc34537ce4c0716d3d0527d0af5c03ee3ef$
//

#include "include/cef_api_hash.h"
#include "libcef_dll/cpptoc/command_line_cpptoc.h"
#include "libcef_dll/cpptoc/scheme_registrar_cpptoc.h"
#include "libcef_dll/ctocpp/app_ctocpp.h"
#include "libcef_dll/ctocpp/browser_process_handler_ctocpp.h"
#include "libcef_dll/ctocpp/render_process_handler_ctocpp.h"
#include "libcef_dll/ctocpp/resource_bundle_handler_ctocpp.h"


// VIRTUAL METHODS FOR VERSION 0 - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void CefApp_0_CToCpp::OnBeforeCommandLineProcessing(const CefString& process_type, CefRefPtr<CefCommandLine> command_line) {
  auto* _struct = GetStruct();
  if (!_struct->on_before_command_line_processing) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: command_line; type: refptr_diff
  DCHECK(command_line.get());
  if (!command_line.get()) {
    return;
  }
  // Unverified params: process_type

  // Execute
  _struct->on_before_command_line_processing(_struct,
      process_type.GetStruct(),
      CefCommandLineCppToC_Wrap(command_line));
}

NO_SANITIZE("cfi-icall") void CefApp_0_CToCpp::OnRegisterCustomSchemes(CefRawPtr<CefSchemeRegistrar> registrar) {
  auto* _struct = GetStruct();
  if (!_struct->on_register_custom_schemes) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: registrar; type: rawptr_diff
  DCHECK(registrar);
  if (!registrar) {
    return;
  }

  // Translate param: registrar; type: rawptr_diff
  auto [registrarPtr, registrarStruct] = CefSchemeRegistrarCppToC_WrapRaw(registrar);

  // Execute
  _struct->on_register_custom_schemes(_struct,
      registrarStruct);
}

NO_SANITIZE("cfi-icall") CefRefPtr<CefResourceBundleHandler> CefApp_0_CToCpp::GetResourceBundleHandler() {
  auto* _struct = GetStruct();
  if (!_struct->get_resource_bundle_handler) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  auto* _retval = _struct->get_resource_bundle_handler(_struct);

  // Return type: refptr_same
  return CefResourceBundleHandlerCToCpp_Wrap(_retval);
}

NO_SANITIZE("cfi-icall") CefRefPtr<CefBrowserProcessHandler> CefApp_0_CToCpp::GetBrowserProcessHandler() {
  auto* _struct = GetStruct();
  if (!_struct->get_browser_process_handler) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  auto* _retval = _struct->get_browser_process_handler(_struct);

  // Return type: refptr_same
  return CefBrowserProcessHandlerCToCpp_Wrap(_retval);
}

NO_SANITIZE("cfi-icall") CefRefPtr<CefRenderProcessHandler> CefApp_0_CToCpp::GetRenderProcessHandler() {
  auto* _struct = GetStruct();
  if (!_struct->get_render_process_handler) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  auto* _retval = _struct->get_render_process_handler(_struct);

  // Return type: refptr_same
  return CefRenderProcessHandlerCToCpp_Wrap(_retval);
}

// CONSTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefApp_0_CToCpp::CefApp_0_CToCpp() {
  const int version = cef_api_version();
  LOG_IF(FATAL, version < 0) << __func__ << " called with invalid version " << version;
}

// DESTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefApp_0_CToCpp::~CefApp_0_CToCpp() {
}

template<> cef_app_0_t* CefCToCppRefCounted<CefApp_0_CToCpp, CefApp, cef_app_0_t>::UnwrapDerived(CefWrapperType type, CefApp* c) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefWrapperType CefCToCppRefCounted<CefApp_0_CToCpp, CefApp, cef_app_0_t>::kWrapperType = WT_APP;


