// Copyright (c) 2015 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#include "libcef_dll/cpptoc/print_dialog_callback_cpptoc.h"
#include "libcef_dll/cpptoc/print_job_callback_cpptoc.h"
#include "libcef_dll/cpptoc/print_settings_cpptoc.h"
#include "libcef_dll/ctocpp/print_handler_ctocpp.h"


// VIRTUAL METHODS - Body may be edited by hand.

void CefPrintHandlerCToCpp::OnPrintSettings(
    CefRefPtr<CefPrintSettings> settings, bool get_defaults) {
  if (CEF_MEMBER_MISSING(struct_, on_print_settings))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: settings; type: refptr_diff
  DCHECK(settings.get());
  if (!settings.get())
    return;

  // Execute
  struct_->on_print_settings(struct_,
      CefPrintSettingsCppToC::Wrap(settings),
      get_defaults);
}

bool CefPrintHandlerCToCpp::OnPrintDialog(bool has_selection,
    CefRefPtr<CefPrintDialogCallback> callback) {
  if (CEF_MEMBER_MISSING(struct_, on_print_dialog))
    return false;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: callback; type: refptr_diff
  DCHECK(callback.get());
  if (!callback.get())
    return false;

  // Execute
  int _retval = struct_->on_print_dialog(struct_,
      has_selection,
      CefPrintDialogCallbackCppToC::Wrap(callback));

  // Return type: bool
  return _retval?true:false;
}

bool CefPrintHandlerCToCpp::OnPrintJob(const CefString& document_name,
    const CefString& pdf_file_path, CefRefPtr<CefPrintJobCallback> callback) {
  if (CEF_MEMBER_MISSING(struct_, on_print_job))
    return false;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: document_name; type: string_byref_const
  DCHECK(!document_name.empty());
  if (document_name.empty())
    return false;
  // Verify param: pdf_file_path; type: string_byref_const
  DCHECK(!pdf_file_path.empty());
  if (pdf_file_path.empty())
    return false;
  // Verify param: callback; type: refptr_diff
  DCHECK(callback.get());
  if (!callback.get())
    return false;

  // Execute
  int _retval = struct_->on_print_job(struct_,
      document_name.GetStruct(),
      pdf_file_path.GetStruct(),
      CefPrintJobCallbackCppToC::Wrap(callback));

  // Return type: bool
  return _retval?true:false;
}

void CefPrintHandlerCToCpp::OnPrintReset() {
  if (CEF_MEMBER_MISSING(struct_, on_print_reset))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  struct_->on_print_reset(struct_);
}


#ifndef NDEBUG
template<> base::AtomicRefCount CefCToCpp<CefPrintHandlerCToCpp,
    CefPrintHandler, cef_print_handler_t>::DebugObjCt = 0;
#endif

