// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=0cb9c52d74603c152ecfe06d00cdb58a87d5b632$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_STORAGE_STATE_ACTION_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_STORAGE_STATE_ACTION_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_storage_state.h"
#include "include/capi/cef_storage_state_capi_versions.h"
#include "include/cef_browser.h"
#include "include/capi/cef_browser_capi_versions.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefStorageStateActionCallback_0_CToCpp
    : public CefCToCppRefCounted<CefStorageStateActionCallback_0_CToCpp, CefStorageStateActionCallback, cef_storage_state_action_callback_0_t> {
 public:
  CefStorageStateActionCallback_0_CToCpp();
  virtual ~CefStorageStateActionCallback_0_CToCpp();

  // CefStorageStateActionCallback methods.
  void OnComplete(bool success, const CefString& error, const CefString& path) override;
};

constexpr auto CefStorageStateActionCallbackCToCpp_Wrap = CefStorageStateActionCallback_0_CToCpp::Wrap;
constexpr auto CefStorageStateActionCallbackCToCpp_Unwrap = CefStorageStateActionCallback_0_CToCpp::Unwrap;

#endif  // CEF_LIBCEF_DLL_CTOCPP_STORAGE_STATE_ACTION_CALLBACK_CTOCPP_H_
