// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=619ebe936401872a471f8784323987d7cc7ca63d$
//

#include "include/cef_api_hash.h"
#include "libcef_dll/cpptoc/list_value_cpptoc.h"
#include "libcef_dll/ctocpp/storage_state_list_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"


// VIRTUAL METHODS FOR VERSION 0 - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void CefStorageStateListCallback_0_CToCpp::OnComplete(bool success, const CefString& error, CefRefPtr<CefListValue> entries, const CefString& directory) {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->on_complete) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: error, entries, directory

  // Execute
  _struct->on_complete(_struct,
      success,
      error.GetStruct(),
      CefListValueCppToC_Wrap(entries),
      directory.GetStruct());
}

// CONSTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefStorageStateListCallback_0_CToCpp::CefStorageStateListCallback_0_CToCpp() {
  const int version = cef_api_version();
  LOG_IF(FATAL, version < 0) << __func__ << " called with invalid version " << version;
}

// DESTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefStorageStateListCallback_0_CToCpp::~CefStorageStateListCallback_0_CToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template<> cef_storage_state_list_callback_0_t* CefCToCppRefCounted<CefStorageStateListCallback_0_CToCpp, CefStorageStateListCallback, cef_storage_state_list_callback_0_t>::UnwrapDerived(CefWrapperType type, CefStorageStateListCallback* c) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefWrapperType CefCToCppRefCounted<CefStorageStateListCallback_0_CToCpp, CefStorageStateListCallback, cef_storage_state_list_callback_0_t>::kWrapperType = WT_STORAGE_STATE_LIST_CALLBACK;


