// Copyright 2026 The Chromium Embedded Framework Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CEF_LIBCEF_DLL_BOOTSTRAP_INSTALLER_INSTALLER_RESOURCES_H_
#define CEF_LIBCEF_DLL_BOOTSTRAP_INSTALLER_INSTALLER_RESOURCES_H_

// Progress dialog resources (200-299 range)
#define IDD_INSTALLER_PROGRESS 200
#define IDC_INSTALLER_STEP 201
#define IDC_INSTALLER_PROGRESS 202
#define IDC_INSTALLER_CANCEL 203
#define IDC_INSTALLER_PERCENT 204

// Progress dialog strings
#define IDS_INSTALLER_TITLE 210
#define IDS_INSTALLER_STEP_INITIALIZING 211
#define IDS_INSTALLER_STEP_CHECKING 212
#define IDS_INSTALLER_STEP_DOWNLOADING 213
#define IDS_INSTALLER_STEP_EXTRACTING 214
#define IDS_INSTALLER_STEP_VERIFYING 215
#define IDS_INSTALLER_STEP_INSTALLING 216
#define IDS_INSTALLER_STEP_COMMITTING 217
#define IDS_INSTALLER_STEP_CLEANING 218
#define IDS_INSTALLER_CANCEL 219
#define IDS_INSTALLER_ERROR_TITLE 220
#define IDS_INSTALLER_PERCENT_FORMAT 221
#define IDS_INSTALLER_ERROR_MESSAGE_FORMAT 222
#define IDS_INSTALLER_ERROR_MESSAGE_CONFIG 223
#define IDS_INSTALLER_ERROR_MESSAGE_NETWORK 224
#define IDS_INSTALLER_ERROR_MESSAGE_VERIFICATION 225
#define IDS_INSTALLER_ERROR_MESSAGE_COMPATIBILITY 226
#define IDS_INSTALLER_ERROR_MESSAGE_BUSY 227
#define IDS_INSTALLER_ERROR_MESSAGE_POLICY 228
#define IDS_INSTALLER_ERROR_MESSAGE_GENERIC 229

#endif  // CEF_LIBCEF_DLL_BOOTSTRAP_INSTALLER_INSTALLER_RESOURCES_H_
