// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=67184afc340a4350aca928442a2929b55017c038$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_TEST_TEST_SERVER_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_TEST_TEST_SERVER_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/test/cef_test_server.h"
#include "include/capi/test/cef_test_server_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefTestServer_0_CppToC
    : public CefCppToCRefCounted<CefTestServer_0_CppToC, CefTestServer, cef_test_server_0_t> {
 public:
  CefTestServer_0_CppToC();
  virtual ~CefTestServer_0_CppToC();
};

constexpr auto CefTestServerCppToC_Wrap = CefTestServer_0_CppToC::Wrap;
constexpr auto CefTestServerCppToC_Unwrap = CefTestServer_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_TEST_TEST_SERVER_CPPTOC_H_
