// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=92c5009e72ba0eb8867dbd8d3dc587a9193895f2$
//

#include "include/cef_api_hash.h"
#include "libcef_dll/cpptoc/test/translator_test_scoped_library_child_child_cpptoc.h"

// GLOBAL FUNCTIONS - Body may be edited by hand.

CEF_EXPORT cef_translator_test_scoped_library_child_child_0_t* cef_translator_test_scoped_library_child_child_create(int value, int other_value, int other_other_value) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  CefOwnPtr<CefTranslatorTestScopedLibraryChildChild> _retval = CefTranslatorTestScopedLibraryChildChild::Create(
      value,
      other_value,
      other_other_value);

  // Return type: ownptr_same
  return CefTranslatorTestScopedLibraryChildChildCppToC_WrapOwn(std::move(_retval));
}

namespace {

// MEMBER FUNCTIONS FOR VERSION 0 - Body may be edited by hand.

int CEF_CALLBACK translator_test_scoped_library_child_child_get_other_other_value(struct _cef_translator_test_scoped_library_child_child_0_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int _retval = CefTranslatorTestScopedLibraryChildChild_0_CppToC::Get(self)->GetOtherOtherValue();

  // Return type: simple
  return _retval;
}

void CEF_CALLBACK translator_test_scoped_library_child_child_set_other_other_value(struct _cef_translator_test_scoped_library_child_child_0_t* self, int value) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefTranslatorTestScopedLibraryChildChild_0_CppToC::Get(self)->SetOtherOtherValue(
      value);
}

int CEF_CALLBACK translator_test_scoped_library_child_child_get_other_value(struct _cef_translator_test_scoped_library_child_0_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int _retval = CefTranslatorTestScopedLibraryChildChild_0_CppToC::Get(reinterpret_cast<cef_translator_test_scoped_library_child_child_0_t*>(self))->GetOtherValue();

  // Return type: simple
  return _retval;
}

void CEF_CALLBACK translator_test_scoped_library_child_child_set_other_value(struct _cef_translator_test_scoped_library_child_0_t* self, int value) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefTranslatorTestScopedLibraryChildChild_0_CppToC::Get(reinterpret_cast<cef_translator_test_scoped_library_child_child_0_t*>(self))->SetOtherValue(
      value);
}

int CEF_CALLBACK translator_test_scoped_library_child_child_get_value(struct _cef_translator_test_scoped_library_0_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int _retval = CefTranslatorTestScopedLibraryChildChild_0_CppToC::Get(reinterpret_cast<cef_translator_test_scoped_library_child_child_0_t*>(self))->GetValue();

  // Return type: simple
  return _retval;
}

void CEF_CALLBACK translator_test_scoped_library_child_child_set_value(struct _cef_translator_test_scoped_library_0_t* self, int value) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefTranslatorTestScopedLibraryChildChild_0_CppToC::Get(reinterpret_cast<cef_translator_test_scoped_library_child_child_0_t*>(self))->SetValue(
      value);
}

}  // namespace

// CONSTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefTranslatorTestScopedLibraryChildChild_0_CppToC::CefTranslatorTestScopedLibraryChildChild_0_CppToC() {
  const int version = cef_api_version();
  LOG_IF(FATAL, version < 0) << __func__ << " called with invalid version " << version;

  GetStruct()->get_other_other_value = translator_test_scoped_library_child_child_get_other_other_value;
  GetStruct()->set_other_other_value = translator_test_scoped_library_child_child_set_other_other_value;
  GetStruct()->base.get_other_value = translator_test_scoped_library_child_child_get_other_value;
  GetStruct()->base.set_other_value = translator_test_scoped_library_child_child_set_other_value;
  GetStruct()->base.base.get_value = translator_test_scoped_library_child_child_get_value;
  GetStruct()->base.base.set_value = translator_test_scoped_library_child_child_set_value;
}

// DESTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefTranslatorTestScopedLibraryChildChild_0_CppToC::~CefTranslatorTestScopedLibraryChildChild_0_CppToC() {
}

template<> CefOwnPtr<CefTranslatorTestScopedLibraryChildChild> CefCppToCScoped<CefTranslatorTestScopedLibraryChildChild_0_CppToC, CefTranslatorTestScopedLibraryChildChild, cef_translator_test_scoped_library_child_child_0_t>::UnwrapDerivedOwn(CefWrapperType type, cef_translator_test_scoped_library_child_child_0_t* s) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefRawPtr<CefTranslatorTestScopedLibraryChildChild> CefCppToCScoped<CefTranslatorTestScopedLibraryChildChild_0_CppToC, CefTranslatorTestScopedLibraryChildChild, cef_translator_test_scoped_library_child_child_0_t>::UnwrapDerivedRaw(CefWrapperType type, cef_translator_test_scoped_library_child_child_0_t* s) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefWrapperType CefCppToCScoped<CefTranslatorTestScopedLibraryChildChild_0_CppToC, CefTranslatorTestScopedLibraryChildChild, cef_translator_test_scoped_library_child_child_0_t>::kWrapperType = WT_TRANSLATOR_TEST_SCOPED_LIBRARY_CHILD_CHILD;


