// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=baad2147b8edbb9d82586b5c99f398f24923cf4b$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_MEDIA_ROUTER_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_MEDIA_ROUTER_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_media_router.h"
#include "include/capi/cef_media_router_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefMediaRouter_0_CppToC
    : public CefCppToCRefCounted<CefMediaRouter_0_CppToC, CefMediaRouter, cef_media_router_0_t> {
 public:
  CefMediaRouter_0_CppToC();
  virtual ~CefMediaRouter_0_CppToC();
};

constexpr auto CefMediaRouterCppToC_Wrap = CefMediaRouter_0_CppToC::Wrap;
constexpr auto CefMediaRouterCppToC_Unwrap = CefMediaRouter_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_MEDIA_ROUTER_CPPTOC_H_
