// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=0cbf7e833f28b6972488a7b8debcf0a89921e4bd$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_NAVIGATION_ENTRY_VISITOR_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_NAVIGATION_ENTRY_VISITOR_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/cef_browser.h"
#include "include/capi/cef_browser_capi.h"
#include "include/cef_client.h"
#include "include/capi/cef_client_capi.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class CefNavigationEntryVisitorCppToC
    : public CefCppToCRefCounted<CefNavigationEntryVisitorCppToC, CefNavigationEntryVisitor, cef_navigation_entry_visitor_t> {
 public:
  CefNavigationEntryVisitorCppToC();
  virtual ~CefNavigationEntryVisitorCppToC();
};

constexpr auto CefNavigationEntryVisitorCppToC_Wrap = CefNavigationEntryVisitorCppToC::Wrap;
constexpr auto CefNavigationEntryVisitorCppToC_Unwrap = CefNavigationEntryVisitorCppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_NAVIGATION_ENTRY_VISITOR_CPPTOC_H_
