// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=2dfa127d91484c9065912ee97e289eb51f07aace$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_REQUEST_CONTEXT_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_REQUEST_CONTEXT_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_request_context.h"
#include "include/capi/cef_request_context_capi_versions.h"
#include "include/cef_request_context_handler.h"
#include "include/capi/cef_request_context_handler_capi_versions.h"
#include "include/cef_scheme.h"
#include "include/capi/cef_scheme_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefRequestContext_0_CppToC
    : public CefCppToCRefCounted<CefRequestContext_0_CppToC, CefRequestContext, cef_request_context_0_t> {
 public:
  CefRequestContext_0_CppToC();
  virtual ~CefRequestContext_0_CppToC();
};

// Wrap a C++ class with a C structure at API version 13401.
// This class may be instantiated and accessed DLL-side only.
class CefRequestContext_13401_CppToC
    : public CefCppToCRefCounted<CefRequestContext_13401_CppToC, CefRequestContext, cef_request_context_13401_t> {
 public:
  CefRequestContext_13401_CppToC();
  virtual ~CefRequestContext_13401_CppToC();
};

// Wrap a C++ class with a C structure at API version 14400.
// This class may be instantiated and accessed DLL-side only.
class CefRequestContext_14400_CppToC
    : public CefCppToCRefCounted<CefRequestContext_14400_CppToC, CefRequestContext, cef_request_context_14400_t> {
 public:
  CefRequestContext_14400_CppToC();
  virtual ~CefRequestContext_14400_CppToC();
};

// Helpers to return objects at the globally configured API version.
cef_request_context_0_t* CefRequestContextCppToC_Wrap(CefRefPtr<CefRequestContext> c);
CefRefPtr<CefRequestContext> CefRequestContextCppToC_Unwrap(cef_request_context_0_t* s);

#endif  // CEF_LIBCEF_DLL_CPPTOC_REQUEST_CONTEXT_CPPTOC_H_
