// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=72baa495ccd8281b81f3cc84357269337a77aa44$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_V8_STACK_TRACE_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_V8_STACK_TRACE_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_v8.h"
#include "include/capi/cef_v8_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefV8StackTrace_0_CppToC
    : public CefCppToCRefCounted<CefV8StackTrace_0_CppToC, CefV8StackTrace, cef_v8_stack_trace_0_t> {
 public:
  CefV8StackTrace_0_CppToC();
  virtual ~CefV8StackTrace_0_CppToC();
};

constexpr auto CefV8StackTraceCppToC_Wrap = CefV8StackTrace_0_CppToC::Wrap;
constexpr auto CefV8StackTraceCppToC_Unwrap = CefV8StackTrace_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_V8_STACK_TRACE_CPPTOC_H_
